# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build

variables:
  TARGET_IMAGE_LATEST: $REGISTRY_ADDR/jbml/no-fish:latest
  TARGET_IMAGE_COMMIT: $REGISTRY_ADDR/jbml/no-fish:latest
  DOCKER_DRIVER: overlay2

build:
  image: docker:stable
  stage: build
  script:
    - echo "docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_ADDR"
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_ADDR
    - docker pull $TARGET_IMAGE_LATEST || true   # for docker build caching
    - docker build --cache-from $TARGET_IMAGE_LATEST --tag $TARGET_IMAGE_LATEST .
    - docker push $TARGET_IMAGE_LATEST
    - docker build --tag $TARGET_IMAGE_COMMIT .
    - docker push $TARGET_IMAGE_COMMIT

