replicaCount: 1
image:
  repository: registry.gitlab.com/jbml/no-fish
  tag: master
  pullPolicy: Always
service:
  name: no-fish
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000
ingress:
  enabled: true
  host: hundunlin.com
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://oceanex.cc,http://test-ocean.com,http://localhost:4200"
    cert-manager.io/cluster-issuer: hundunlin-prod
  tls:
    - secretName: star-oceanex-cc-tls
      hosts:
        - hundunlin.com
        - www.hundunlin.com
app:
  vars:
    FISH_DB_NAME: fish_production
    FISH_DB_USER: root
    FISH_DB_PASSWORD: changeme
    FISH_DB_HOST: mysql.kube-services
    FISH_DB_PORT: 3306

