deploymentApiVersion: apps/v1
replicaCount: 1
image:
  repository: registry.gitlab.com/jbml/no-fish
  tag: master
  pullPolicy: Always
service:
  name: fish
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000
ingress:
  enabled: true
  host: hundunlin.com
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: hundunlin-prod
  tls:
    - secretName: secret-fish-tls
      hosts:
        - hundunlin.com
        - www.hundunlin.com
        - fish.hundunlin.com
app:
  vars:
    FISH_DB_NAME: fish_production
    FISH_DB_USER: root
    FISH_DB_PASSWORD: changeme
    FISH_DB_HOST: mysql.kube-services
    FISH_DB_PORT: 3306

