# Generated by Django 3.2.6 on 2021-09-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='picture',
        ),
        migrations.AddField(
            model_name='detail',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.photo'),
        ),
    ]
