# Generated by Django 3.2.6 on 2021-09-06 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210902_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 8, 7, 51, 513718), verbose_name='created'),
        ),
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
