# Generated by Django 3.2.6 on 2021-09-06 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210906_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 8, 8, 35, 244855, tzinfo=utc), verbose_name='created'),
        ),
    ]
