# Generated by Django 3.2.6 on 2021-09-06 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_photo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
